#!/usr/bin/env python

import os
import argparse
import re

TITLE_REGEX = re.compile("\s+<title>(.*)<\/title>$")
END_REGEX = re.compile("\s+<\/page>$")
MAGIC_REGEX = re.compile("{{#invoke.*?}}", re.MULTILINE)
TITLES = set()

SKIP = [
    "Stripe-headed round-eared bat",
    "Chromolaena odorata",
    "Termez",
    "Punjab Engineering College",
    "New York Mets award winners and league leaders",
    "Home Ministry",
    "Kristina Lilley",
    "OBJ",
    "Debate on traditional and simplified Chinese characters",
    "Melita F.C.",
    "Chuck Hazama",
    "Augustin-Joseph de Mailly",
    "Tikota",
    "Sahu Jats",
    "Timelines of Ottoman Syria history",
    "Superman curse",
    "Garud Commando Force",
    "Hiba Tawaji",
    "Nanganur",
    "Olojo festival",
    "Piko (singer)",
    "Maanagara Kaaval",
    "1932 in Mandatory Palestine",
    "1926 in Mandatory Palestine",
    "Demographics of the world",
    "E.tv News",
    "Yury Khovansky",
    "Donald Brown (defensive back)",
    "List of serving generals of the Bangladesh Army",
    "Anshel Pfeffer",
    "Donkey Kong (character)",
    "Big Magic",
    "Timeline of Eastern philosophers",
    "Intelligence Bureau (India)",
    "Kathua",
    "HD 89345 b",
    "EReality",
    "Liss (band)",
    "Index of Shenzhen-related articles",
    "Ekhane Aakash Neel Season 2",
]

def main():
    """Run the main program"""

    desc = """\
Remove duplicate titles from a wikimedia dump.

This script will scan through a wikimeda dump. Any duplicate titles will be
skipped. This script creates a temporary file and then replaces the original
file.

Beware that the temporary file is roughly the same size as the original, so
make sure you have enough space on the device to temporary duplicate the file.
"""

    parser = argparse.ArgumentParser(
        description=desc, formatter_class=argparse.RawTextHelpFormatter)
    parser.add_argument(
        "input", metavar="<intput file>", help="the input file to parse"
    )

    args = parser.parse_args()

    tmp_file = args.input + ".tmp"
    # Signal whether the title should be skipped
    skip = False
    try:
        output = open(tmp_file, "w")
        with open(args.input) as _file:
            for line in _file:
                if skip:
                    if END_REGEX.match(line):
                        skip = False
                    continue

                # Strip out unsupported magic template
                line = MAGIC_REGEX.sub("", line)

                # Check for a duplicated file
                match = TITLE_REGEX.match(line)
                if match:
                    title = match.group(1)
                    if title in SKIP:
                        print("Skipping title: " + title)
                        skip = True
                        continue
                    if title in TITLES:
                        print("Duplicate title: " + title)
                        skip = True
                        continue
                    TITLES.add(title)
                output.write(line)
        # Replace the old file with the deduped file
        os.rename(tmp_file, args.input)
    except KeyboardInterrupt:
        pass
    finally:
        # Cleanup if necessary
        if os.path.exists(tmp_file):
            os.remove(tmp_file)

main()
